language: python
python:
- "3.5"
install: pip install -r requirements.txt
script: nosetests
install: pip install coverage
install: pip install nose
script: nosetests --with-coverage --cover-package=tests && coverage report
after_success: coveralls